import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { raleway } from "@/lib/fonts";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import AuthSessionProvider from "@/providers/AuthProvider";
import FirebaseAuthProvider from "@/providers/FirebaseAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  createTask: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthSessionProvider>
        <FirebaseAuthProvider>
          <body className={`${raleway.className}  bg-gray-900 `}>
            <Navbar />
            {props.createTask}
            {props.children}
          </body>
        </FirebaseAuthProvider>
      </AuthSessionProvider>
    </html>
  );
}
